### ISSUE TITLE
autoscale.log rotate not working

### ISSUE THREAD

**Issue by themorey** [Azure/cyclecloud-gridengine#24]
CC: 8.1.1-1451
Grid proj: 2.0.1
UGE:  8.6.7

The `autoscale.log` is not rotating and is filling the disk:

```
[root@chainlink jetpack]# ls -lh logs
total 242G
-rw-rw-r--. 1 cyclecloud cyclecloud 242G Jun 17 16:42 autoscale.log
```

Per the `/opt/cycle/gridengine/logging.conf` file the log should rotate at 5MB:

```
[handler_fileHandler]
class=logging.handlers.RotatingFileHandler
level=DEBUG
formatter=simpleFormatter
args=("/opt/cycle/jetpack/logs/autoscale.log",)
kwargs={"maxBytes": 1024 * 1024 * 5, "backupCount": 5}
```

**Comment by ryanhamel** [comment]
This is fixed in 2.0.7. The fix required is below, in bold. Notice the kwargs line is removed.

[handler_fileHandler]
class=logging.handlers.RotatingFileHandler
level=DEBUG
formatter=simpleFormatter
**args=("/opt/cycle/jetpack/logs/autoscale.log", "a", 1024 * 1024 * 5, 5)**

[handler_qcmdHandler]
class=logging.handlers.RotatingFileHandler
level=DEBUG
formatter=simpleFormatter
**args=("/opt/cycle/jetpack/logs/qcmd.log", "a", 1024 * 1024 * 5, 5)**
